apiVersion: apps/v1
kind: Deployment
metadata:
  name: gromm-api
spec:
  selector:
    matchLabels:
      app: gromm-api
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gromm-api
    spec:
      containers:
      - name: gromm-api
        env:
        - name: THOR_URL
          value: https://rpc-testnet.vechain.energy/
        - name: CHAIN_ID
          value: 100010
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: vchain-thor
              key: private_key
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "128Mi"
            cpu: "20m"
          limits:
            memory: "1Gi"
      restartPolicy: Always
      imagePullSecrets:
      - name: ghcr-registry
status: {}