apiVersion: v1
kind: Service
metadata:
  name: thor-node-service
spec:
  selector:
    app: thor-node
  ports:
    - name: api
      port: 8669
      targetPort: 8669
      protocol: TCP
    - name: p2p
      port: 11235
      targetPort: 11235
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gromm-api
spec:
  type: ClusterIP
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: gromm-api
status:
  loadBalancer: {}