apiVersion: v1
kind: Service
metadata:
  name: thor-node-service
spec:
  selector:
    app: thor-node
  ports:
    - name: api
      port: 8669
      targetPort: 8669
      protocol: TCP
    - name: p2p
      port: 11235
      targetPort: 11235
      protocol: TCP
  type: ClusterIP