apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - pvc.yaml

namespace: vchain-staging

patches:
  - path: ./statefulset.yaml
  - path: ./deployment.yaml
