apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vchain-thor-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 30Gi